HomeWork3
artem-burashnikov/2022-Programming-Technologies-F-sharp-course pull request #13
Opened 2022-10-20 00:46 UTC by artem-burashnikov

> Домашняя работа 3. Про деревья.
> 1. Описать алгебраический тип, задающий дерево, в котором внутренний узел может иметь произвольное количество сыновей. Листья и внутренние узлы хранят некоторые значени произвольного (одинакового для всех) типа.
> 2. Реализовать функцию, которая по дереву (тип, описанный выше),  находит количество различных элементов, хранящихся в узлах. Использовать рекурсию, не использовать мутабельные переменные.
> 3. Реализовать функцию, которая по дереву (тип, описанный выше),  строит список, содержащий все значения из всех узлов. Для сипска использовать тип MyList из предыдущей задачи.

## Checklist

- [ ] Создан алгебраический тип, позволяющий хранить произвольное число сыновей для каждого узла.
- [ ] Создана требуемая функция обхода такого типа, конструирующая список и собирающая значения в узлах (объединяет в себе задачи №2 и №3).
- [ ] Реализованы тесты.

## Further comments

Please ignore .fantomasignore  file (pun intended).
For now i plan on using it for Test files only, because the built-in formatting messes up with indentation which makes it harder to add new tests. This later will be resolved by adjusting the necessary settings in Fantomas.

2022-10-21 05:13 UTC, gsvgit requested changes

2022-10-21 05:13 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +    let makeCList (tree: NTree<'value>) =
1. Всё же надо вые отдельные функции. Одна считает уникальные, другая строит список. 
2. Да, две эти функции можно унифицировать, но несколько иначе, чем Вы сечас это делаете.

2022-10-21 05:13 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +            let rec visit family =
Разве это не выражается через какой-нибудь ```map```?

2022-10-21 05:24 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +            let rec visit family =
Что именно? Вопрос не понял.

2022-10-21 05:28 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +    let makeCList (tree: NTree<'value>) =
> 1. Всё же надо вые отдельные функции. Одна считает уникальные, другая строит список.
Зачем?.. Два раза придется проходить дерево...
>     2. Да, две эти функции можно унифицировать, но несколько иначе, чем Вы сечас это делаете.
Вы имеете в виду сделать "аналог" map, чтобы можно было передавать функции?

2022-10-21 05:59 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +    let makeCList (tree: NTree<'value>) =
1. А давайте сделаем одну функцию с миллионом параметров, которая считает всё.
2. Скорее fold.

2022-10-21 05:59 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +            let rec visit family =
Вся функция visit. Кажется, Вам просто нужен map по списку сыновей.

2022-10-21 20:22 UTC, artem-burashnikov commented
Не стал писать комментарии в коде в этот раз, потому что как будто бы там нечего писать.
Обычно можно как-то пояснить идею без повторения самого кода. А в данном случае никакой глубокой идеи в коде нет, просто есть fold, который я попытался корректно написать.

2022-10-22 00:06 UTC, artem-burashnikov commented
- [x] Переработана функция обхода дерева таким образом, чтобы она могла принимать другие функции.
- [x] Реализованы отдельные функции, позволяющие решить задачи №2 и №3, передав эти функции основной фукнции обхода дерева.

2022-10-22 11:34 UTC, artem-burashnikov commented
@gsvgit fMerge, кажется, и не вызывается. Изначально там была другая "реализация", и идея заключалась в том, чтобы добавлять в аккумулятор значения из других рекурсивных вызовов, но она не работала. А потом я начал усекать лишнее. Но если подумать о том, как работает fold, то одной функции folder (в моём случае fAdd) должно быть достаточно). В некотором случае на сам аккумулятор еще применяется тот же fold (когда у узла, являющегося чьим-то сыном, есть собственные сыновья). Поэтому, видимо, кусок fold fAdd fMerge на самом деле сокращался до куска fold fAdd, что просто можно обозвать fold folder.

2022-10-22 15:18 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +            match children with
Кажется, все ещё сложновато написано. Держа в руках узел Вы должны свернуть всех его детей и не потерять value. Зачем вручную декомпозировать детей? Фолд на списке сам справится.

2022-10-22 15:53 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +            match children with
Да, красота, в две строчки получается.

2022-10-22 16:52 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +            match children with
А теперь стало понятнее, почему оно работает?

2022-10-22 17:13 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +            match children with
Да, работа fold меня не смущает, меня смущала запись
let recurse = fold fAdd fMerge и почему ей было дозволено существовать. Но, видимо, просто такой язык, что такое дозволено.

2022-10-22 17:25 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +            match children with
А. Так можно и без неё. Видимо, такой стиль записи Вы просто где-то подсмотрели.

2022-10-22 17:33 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +            match children with
Ага, https://fsharpforfunandprofit.com/posts/recursive-types-and-folds-2b/

2022-10-22 17:35 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +            match children with
Я еще думал, как обернуть свёртку в обратную сторону, но не придумал.

2022-10-24 06:13 UTC, gsvgit commented on src/spbu-fsharp/Task3.fs
> +    // HomeWork 3 result..
Ээх.. Ещё раз. В домашке было всё таки две отдельные функции.

2022-10-24 09:08 UTC, artem-burashnikov commented on src/spbu-fsharp/Task3.fs
> +    // HomeWork 3 result..
D:

2022-10-24 14:43 UTC, gsvgit approved these changes

2022-10-24 15:05 UTC, merged