BFS
artem-burashnikov/2022-Programming-Technologies-F-sharp-course pull request #16
Opened 2022-11-27 12:06 UTC by artem-burashnikov

> 1. Реализовать над SparseVector, SparseMatrix необходимые для реализации обхода в ширину операции (маску, поэлементные операции с вектором). Маской может быть любой вектор. Поэлементная операция может быть любой.
> 2. Реализовать алгоритм обхода в ширину, используя матрично-векторные операции. Не забыть про то, что алгоритм обхода в ширину —- это алгоритм обхода графа, а не просто набор операций над матрицами и векторами.
> 3. Добавить тесты как на отдельные операции, так и на обход в ширину целиком.

2022-11-27 12:13 UTC, artem-burashnikov commented
### Конвертация из представления матрицы в виде координат в дерево квадрантов
- [x] Функция разделения на квадранты
- [ ] Тесты
- [x] Функция ковертации в дерево
- [ ] Тесты

2022-12-11 18:52 UTC, artem-burashnikov commented
- [ ] Реализован конвертер из кооридинатного представления вектора в разреженный + тест.
- [ ] Реализован конвертер из координатного представления матрицы в разреженную + тест.

2022-12-12 22:42 UTC, artem-burashnikov commented
- [ ] Реализован BFS + тест через наивную реализацию.

2022-12-13 06:14 UTC, gsvgit commented on tests/spbu-fsharp.Tests/spbu-fsharp.Tests.fsproj
> +<!--        <Compile Include="Task1Tests.fs" />-->
А что остальные тесты вырубили? Не работают?

2022-12-13 06:14 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | QuadTree.Node(QuadTree.None, QuadTree.None, QuadTree.None, QuadTree.None) -> QuadTree.None
Где-то я такое уже видел. Почему оно здесь как что-то новое появляется?

2022-12-13 06:14 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | Some true, _
А правда ли, что Вам именно булев тип нужен?

2022-12-13 15:30 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/spbu-fsharp.Tests.fsproj
> +<!--        <Compile Include="Task1Tests.fs" />-->
Так быстрее было работать. Вернул.

2022-12-13 15:30 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | QuadTree.Node(QuadTree.None, QuadTree.None, QuadTree.None, QuadTree.None) -> QuadTree.None
Вынес наружу.

2022-12-13 19:34 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Some true, _
Пока такие направления мыслей:
1) Сделать Some _, Some _
2) Сделать инты
3) Сделать свой тип
4) Вопрос более общий и про что-то другое, над чем надо еще подумать.

2022-12-14 06:55 UTC, gsvgit requested changes

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task4.fs
> +    (*
А зачем? Не работает? Вообще, при наличии системы контроля версий комментить куски кода --- сомнительное занятие.

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task4.fs
> +    (*
Ну и тут что-то странное.

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task4.fs
> -            | BinTree.None, BinTree.Node(b1, b2) -> BinTree.Node(inner bTree1 b1, inner bTree1 b2) |> VectorData.reduce
Вообще, изначальный вариант как-то лучше читается.

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        val Data: List<int * int * 'a option>
Угловые скобки....

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        val Data: List<int * 'a>
А почему в матрице сказано, что ячейка обязательно Option, а тут уже нет?

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | _ -> failwith $"fUpdateCount: Unexpected result.\nGiven a:%A{a}\nGiven b:%A{b}"
Ну вот почему он unexpected? Такие знаяниея могут быть в векторах? Могут.... Операция к ним может быть применениа? Что-то тут не так.

2022-12-14 06:55 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        COOVector(List.map (fun x -> (x, value)) lst, size)
Почти изобрели init.

2022-12-14 06:55 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                  let startV = List.map (fun i -> abs i % size) ints |> List.distinct
Ах если бы был такой тип, в котором нет отрицательных значений....

2022-12-14 10:22 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        val Data: List<int * 'a>
А что значит в векторе значение none? Тогда и координату писать не было смысла.

2022-12-14 11:14 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Some true, _
Нет, инт здесь удобнее.

2022-12-14 15:58 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | _ -> failwith $"fUpdateCount: Unexpected result.\nGiven a:%A{a}\nGiven b:%A{b}"
В моей конкретной реализации такой матч произойти не должен, мне было удобно проверить, что все корретно.

2022-12-14 16:18 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        val Data: List<int * int * 'a option>
Партизаны.

2022-12-14 19:41 UTC, artem-burashnikov commented on src/spbu-fsharp/Task4.fs
> -            | BinTree.None, BinTree.Node(b1, b2) -> BinTree.Node(inner bTree1 b1, inner bTree1 b2) |> VectorData.reduce
Поправил.

2022-12-14 19:41 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Some true, _
Согласен, что не нужен.

2022-12-14 19:42 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        val Data: List<int * 'a>
Поправил.

2022-12-14 19:42 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | _ -> failwith $"fUpdateCount: Unexpected result.\nGiven a:%A{a}\nGiven b:%A{b}"
Поправил.

2022-12-14 22:01 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                  let startV = List.map (fun i -> abs i % size) ints |> List.distinct
:sob:

2022-12-14 22:28 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        COOVector(List.map (fun x -> (x, value)) lst, size)
Попробовал доизобрести.

2022-12-14 22:29 UTC, artem-burashnikov commented
- [ ] Переписать наивный BFS через встроенную коллекцию Queue<'T>

2022-12-15 06:21 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        let rec inner (frontier: SparseVector<Option<uint>>) (visited: SparseVector<Option<uint>>) (counter: uint) =
То есть если bool для фронта --- слишком много, то uint --- в самый раз?

2022-12-15 06:21 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        let visited = COOVector.Init startV length (Some 0u) |> Converter.cooToSparseVec
Ну такое. Посомртире на сигнатуру типисного init.

2022-12-15 06:21 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                if List.contains vertex visited then
Какова сложность проверки наличия элемента в списке?

2022-12-15 06:41 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                if List.contains vertex visited then
Надо что-то хэшанутое, значится.

2022-12-15 06:45 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                if List.contains vertex visited then
Ну или хотя бы деревообразное.

2022-12-15 06:57 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        let rec inner (frontier: SparseVector<Option<uint>>) (visited: SparseVector<Option<uint>>) (counter: uint) =
Some uint / None
Хм...

2022-12-15 18:19 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task5Tests.fs
> +                if List.contains vertex visited then
Set<'T>

2022-12-15 19:22 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        let rec inner (frontier: SparseVector<Option<uint>>) (visited: SparseVector<Option<uint>>) (counter: uint) =
()

2022-12-15 19:22 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        let visited = COOVector.Init startV length (Some 0u) |> Converter.cooToSparseVec
Не то, что надо, мне кажется.

2022-12-17 04:54 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Меня несколько смущает эта конструкция. Какой у Вас тип для `visited` в итоге получается?

2022-12-17 04:54 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +            if newFrontier.IsEmpty then
Есть ощущение, что проверку фронта на пустоту можно делать всего в одном месте, а не в двух. Кода будет чуть меньше.

2022-12-17 09:16 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
![image](https://user-images.githubusercontent.com/94160707/208234795-e9d04685-07b0-4b95-8237-3a5079c64d20.png)
Почему там так: У нас в дереве хранятся Some/Option, а сложение векторов учитывает случай, когда в листьях лежат обычные значения.
То есть сложение выглядит так 
![image](https://user-images.githubusercontent.com/94160707/208234866-38c0c4c1-abc9-4bf1-8c8c-252a6a30a17f.png)
Обратите внимание, что оборачивается в Some/None и передается функции fDo. Лишний Some/None потом снимается и результат кладется в лист.

2022-12-17 10:11 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Ну и, собственно, поменять можно, если тут инициализировать просто 0u вместо Some 0u.
![image](https://user-images.githubusercontent.com/94160707/208236831-7d78ab94-5eba-455d-91b3-c0b3d1c55d80.png)

Тогда в функции fUpdateCount один сам можно убрать.

2022-12-19 05:58 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Так вот "можно" или таки "нужно"? Что-то у Вас все ещё какая-то каша с типами.

2022-12-19 06:32 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Почему каша-то? Везде option.

2022-12-19 07:56 UTC, gsvgit commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Что? visited --- это же просто разметка галочками "посетили на i-ой итерации -- не посетили". Какой None?

2022-12-19 08:07 UTC, artem-burashnikov commented on src/spbu-fsharp/Task5.fs
> +        | Option.None, Some _ -> Some(Some iter)
Поправил.

2022-12-19 08:40 UTC, gsvgit approved these changes
Вымучили

2022-12-19 08:52 UTC, merged