Parallel Vector-Matrix operations
artem-burashnikov/2022-Programming-Technologies-F-sharp-course pull request #18
Opened 2023-01-30 15:20 UTC by artem-burashnikov

## Задачи

> 1. Научиться читать файлы в формате matrixmarket.
> 2. Научиться строить граф на основе прочитанной матрицы смежности. 
> 3. Реализовать параллельные версии матричных и векторных операций.

2023-01-30 15:46 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +    use reader = new StreamReader(filePath)
А чем readalllines не угодил?

2023-01-30 15:56 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +    use reader = new StreamReader(filePath)
Кажется, что это дело будет потом менее удобно обрабатывать, ведь в шапке не фиксированное число коммантариев, судя по спецификации формата.

2023-01-30 16:11 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +    use reader = new StreamReader(filePath)
Ща... Формат файла в любом случае строковый. Прочитали строки, а потом сколько надо, столько и взяли.

2023-01-31 05:33 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
>      let mutable dataLineIndex = 1
А может можно просто [Seq.skipWhile](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#skipWhile)?

2023-02-01 17:46 UTC, artem-burashnikov commented
- [ ] Реализовать чтение файлов в формате matrix market.

2023-02-01 19:18 UTC, artem-burashnikov commented
- [ ] Научиться читать файлы в формате matrixmarket.

2023-02-01 19:22 UTC, artem-burashnikov commented
- [ ] Научиться читать файлы в формате matrixmarket.

2023-02-06 08:20 UTC, gsvgit commented on src/spbu-fsharp/MatrixAlgebra.fs
> +        let rec innerN bTree1 bTree2 =
Кажется, что-то такое было где-то выше.

2023-02-06 08:20 UTC, gsvgit commented on src/spbu-fsharp/MatrixAlgebra.fs
> +            match bTree1, bTree2 with
И это очень похоже. Можно ли как-то не писать одну и ту же логику несколько раз?

2023-02-06 08:20 UTC, gsvgit commented on src/spbu-fsharp/MatrixAlgebra.fs
> +    let parallelVecByMtx
Ну и тут попахивает дублированием.

2023-02-06 08:20 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Pattern then
С одной стороны, решение имеет место быть. С другой --- Вы не можете, например, поднять булев паттерн из интовой матрицы, что странно.

А ещё есть ощущение, что Вы эти методы как следует не тестировали.

2023-02-06 08:20 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Pattern then
Ну да. Чот тестов на ридер как-то не сильно много)

2023-02-06 08:20 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
А есдли не 0? Будет хоть что-то параллелиться?

2023-02-06 09:34 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixAlgebra.fs
> +            match bTree1, bTree2 with
Вы про соединить innerN и innerP или про elementwiseVecVec и parallelElementwiseVecVec?

2023-02-06 09:39 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
> А есдли не 0? Будет хоть что-то параллелиться?

Вы намекаете, что сложение векторов неверно распараллелено?

2023-02-06 09:53 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Ну.... Как минимум, странно,  что тестов нету)

2023-02-06 09:54 UTC, gsvgit commented on src/spbu-fsharp/MatrixAlgebra.fs
> +            match bTree1, bTree2 with
Я про соединить всё, что можно соединить. Зачем дублировать код, если можно не дублировать?

2023-02-06 10:11 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Все, что не 0, работает заметно медленнее... В плане времени выполнения тестов.

2023-02-06 10:11 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
> Ну.... Как минимум, странно, что тестов нету)

Все, что не 0, работает заметно медленнее... В плане времени выполнения тестов.

2023-02-06 11:00 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Ага... Ну и вернёмся к Вашему же вопросу. А верно ли распараллелено тогда?

2023-02-06 11:28 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Ну... Это может быть связано с тем, как работают тесты, например.
Просто, смотря на код, кажется, что все правильно: есть левая ветка дерева, есть правая, которые считаются параллельно.

2023-02-06 11:32 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Ну попробуйте что-то конкретное уже абенчмаркать)

2023-02-06 11:41 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Это еще надо понять, как.

2023-02-06 11:43 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Самое время. Всё равно следующий шаг --- эксперименты.

2023-02-07 14:14 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Pattern then
Хардкодить путь к текстовому файлу для тестов - это насколько нормально?

2023-02-07 20:31 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let result1 = parallelElementwiseVecVec 0 fPlus vec1 vec2
Вроде бы распараллелил. Посмотрите, пожалуйста.

2023-02-07 20:32 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixAlgebra.fs
> +            match bTree1, bTree2 with
Убрал.

2023-02-07 20:32 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixAlgebra.fs
> +        let rec innerN bTree1 bTree2 =
Убрал.

2023-02-07 21:25 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Pattern then
Добавил некоторые тесты.

2023-02-10 23:41 UTC, artem-burashnikov commented
Проблема была не в коде, который отвечал за распараллеливание, а в коде, который отвечал за бенчмарки.

2023-02-15 06:39 UTC, gsvgit requested changes

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/BenchmarkDotNet.Artifacts/results/MyBenchmarks.MatrixAlgebraBenchmarks.MyAddBench-report-github.md
> +|   BaseAdd | 1.394 s | 0.0274 s | 0.0346 s |  1.00 |    0.00 |
А куда делись уровни 0, 1, 3 ?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/Benchmarks.fs
> +        let vec =
А почему матрица `[<GlobalSetup>]`, а вектор --- нет?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/Benchmarks.fs
> +        member this.BaseMult() = vecByMtx 0 fPlus fMult vec mtx
Ага. 0 --- вот он. А 1 и 3 всё ещё где-то потерялись.

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'A when 'A: comparison> = Set<'A>
Лучше типвые переменные тоже как-то вменяемо называть. Это ведь `'Label`?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +                for i = 1 to toIntConv mtx.Rows do
Ой. То есть вершины из разреженной матрицы всегда честно за квадрат?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/Helper.fs
> +            failwith "parseFloat: Invalid input"
Луче сразу показывать, что там за инпут неожиданный такой.

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        | _ -> failwith "Unsupported format type"
Какой? Что там пришло?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        | _ -> failwith "Unsupported object type"
Какой?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +    let sq = Array.toSeq allLines |> Seq.skipWhile (fun line -> line[0] = '%')
А может просто сразу seq читать? А то гоняете туд-обратно

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        if head <> None then
Чот странное. Почему не длина просто?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        Seq.skipWhile (fun (i, j, _) -> i = j) sq |> Seq.map mapping |> Seq.append sq
А правда ли, что диагональ всегда в начале?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Integer then
А можно как-то без дублирования кода обойтись?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/SparseVector.fs
> +                SparseVector(inner computationLevel vec1.Data vec2.Data, vec1.Length)
Так он `parallelLevel` или `computationLevel`?

2023-02-15 06:39 UTC, gsvgit commented on src/spbu-fsharp/SparseVector.fs
> +        static member Map2
А как так получилось, что в дифах нет удаления старого кода про elementWise?

2023-02-15 06:39 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let plusOne = SparseVector.Map2 0 fPlus vec vecOnes
А на больше чем 0 почему бы не потестить? Вообще как-то не вижу тестов на параллельные версии.

2023-02-15 07:59 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        if head <> None then
Длину считать надо, а тут только один элемент проверить. Идея такая.

2023-02-15 08:03 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let plusOne = SparseVector.Map2 0 fPlus vec vecOnes
А каков смысл в тестировании этих функций выше, чем на уровне 0, если этот уровень сам по себе показывает корректность вычислений, а производительность показывают бенчмарки?

2023-02-15 11:12 UTC, artem-burashnikov commented on src/spbu-fsharp/SparseVector.fs
> +        static member Map2
Я изменения сделал в отдельной ветке, а потом скаашнул в эту.
Вот коммит https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/commit/123e2b2d5c9538ce8264dfc19dd40cc9c299aee1

2023-02-15 11:24 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +    let sq = Array.toSeq allLines |> Seq.skipWhile (fun line -> line[0] = '%')
Прочитал в массив, а потом один раз в sequence превратил. Дальше только sequence использую, кажется. ReadLines вроде бы читает в коллекцию, попробую.

2023-02-15 11:40 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'A when 'A: comparison> = Set<'A>
Думаю, что нет. Это имитация множества рёбер. Label это уже то, что на самом ребре.

2023-02-15 11:43 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +                for i = 1 to toIntConv mtx.Rows do
Вершины линейно, ребра за квадрат. Думаю, ребра будет выгоднее обходом дерева собирать через какой-нибудь fold.

2023-02-15 11:51 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Integer then
Вот тут не так просто... Могу только предложить одну функцию, которая будет принимать converter и возвращать помимо всего прочего converter stringValue. Но сделать функцию, которая вернёт или матрицу int, или матрицу float, или какую-то друую не знаю, как. Такого полиморфизма вроде бы и нету.

2023-02-15 13:46 UTC, gsvgit commented on tests/spbu-fsharp.Tests/MatrixAlgebraTests.fs
> +                  let plusOne = SparseVector.Map2 0 fPlus vec vecOnes
А в друг Вы изменяемое состояние неправильно используете?

2023-02-15 13:46 UTC, gsvgit commented on src/spbu-fsharp/SparseVector.fs
> +        static member Map2
А....

2023-02-15 16:39 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        if file.Field <> Integer then
Только если сделать общую функцию, которая извне принимает какой-нибудь converter и возвращает, помимо всего прочего, ``converter valueInStringFormat``

2023-02-15 19:46 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +                for i = 1 to toIntConv mtx.Rows do
Почти такое ощущение, что тут с помощью BFS можно получить ответ.

2023-02-15 19:46 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        Seq.skipWhile (fun (i, j, _) -> i = j) sq |> Seq.map mapping |> Seq.append sq
Нет, это я плохо читаю описание того, что встроенные методы делают...

2023-02-16 15:02 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +        Seq.skipWhile (fun (i, j, _) -> i = j) sq |> Seq.map mapping |> Seq.append sq
Не тот метод применил.

2023-02-16 15:03 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +                for i = 1 to toIntConv mtx.Rows do
Попытался эффективно.

2023-02-16 15:03 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'A when 'A: comparison> = Set<'A>
``'Lable`` мне кажется чем-то другим.

2023-02-16 15:04 UTC, artem-burashnikov commented on src/spbu-fsharp/SparseVector.fs
> +                SparseVector(inner computationLevel vec1.Data vec2.Data, vec1.Length)
``parallelLevel``

2023-02-16 15:05 UTC, artem-burashnikov commented on src/spbu-fsharp/Benchmarks.fs
> +        let vec =
Изменил весь код бенчмарка.

2023-02-20 05:54 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'PairOfVertices when 'PairOfVertices: comparison> = Set<'PairOfVertices>
И при этом это не `Vertex<'A> * Vertex<'A>` Но как? И, главное, зачем?

2023-02-20 05:54 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +        let mutable edges = Set.empty
Напишите уже общую ходилку по матрице типа `fold`, видимо.

2023-02-20 05:54 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +    let allLines = File.ReadLines filePath |> Seq.cast<string>
А `ReadLines` разве не строки читает? Зачем конвертация?

2023-02-20 05:54 UTC, gsvgit commented on tests/spbu-fsharp.Tests/GraphsTests.fs
> +                        if value <> Option.None then
`value.IsNone`

2023-02-20 06:00 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +    let allLines = File.ReadLines filePath |> Seq.cast<string>
Он читает в более общий тип. Нужно или так делать, чтобы дальше работать с seq, или писать '''seq { yield! ... }''', что, кажется делает что-то подобное.

2023-02-20 06:02 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'PairOfVertices when 'PairOfVertices: comparison> = Set<'PairOfVertices>
Вообще, я, кажется, больше головной боли себе создал этими типами.

2023-02-20 06:02 UTC, gsvgit commented on src/spbu-fsharp/MatrixReader.fs
> +    let allLines = File.ReadLines filePath |> Seq.cast<string>
Ээээ .. IEnumerable не сильно более общий)

2023-02-20 06:05 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +    let allLines = File.ReadLines filePath |> Seq.cast<string>
С ним Seq.skipWhile не дружит. Во всяком случае, у меня не получалось подружить. Попробую потыкать ещё что, но...

2023-02-20 06:33 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +type UndirectedEdge<'PairOfVertices when 'PairOfVertices: comparison> = Set<'PairOfVertices>
А хотел, чтобы было издали графоподобное.

2023-02-20 07:10 UTC, artem-burashnikov commented on src/spbu-fsharp/MatrixReader.fs
> +    let allLines = File.ReadLines filePath |> Seq.cast<string>
> Ээээ .. IEnumerable не сильно более общий)

Ахаха, все магическим образом заработало) Это, наверное, один из тех случаев, когда сначала нужно компилятору чуток дальше в коде подсказать, а потом раньше в коде можно ослабить условия.

2023-02-21 06:07 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +        let folder i j _ set = Set.add (Set.ofList [ i; j ]) set
1. Если я правильно понимаю, то метки на рёбрах Вы не сохраняете.
2. Не вплне пнял, что вообще происходит. Почему рёбра --- это что-то типа множества множеств?

2023-02-21 06:21 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +        let folder i j _ set = Set.add (Set.ofList [ i; j ]) set
> 1. Если я правильно понимаю, то метки на рёбрах Вы не сохраняете.
Да, только рёбра.

> 2\. Не вплне пнял, что вообще происходит. Почему рёбра --- это что-то типа множества множеств?

Я пытаюсь подогнать то, что происходит, под определение неориентированного графа.
То есть получить по матрице смежности множество неупорядоченных рёбер.

2023-02-21 06:22 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +        let folder i j _ set = Set.add (Set.ofList [ i; j ]) set
Что?)

2023-02-21 06:22 UTC, artem-burashnikov commented on src/spbu-fsharp/Graphs.fs
> +        let folder i j _ set = Set.add (Set.ofList [ i; j ]) set
?))))

2023-02-21 11:30 UTC, artem-burashnikov commented
Теперь я собираю по матрице множество троек (вершина, вершина, значение).

2023-02-22 05:21 UTC, gsvgit commented on src/spbu-fsharp/Graphs.fs
> +        let folder i j value set = Set.add (i, j, Some value) set
1. А вот на ребре значение всегда ровно то, что в матрице храниться. Не надо его ещё раз в Option заварачивать.
2. А вот тут как раз было бы уместно тип "Ребро" сдеолать аккуратно.

2023-02-23 06:57 UTC, gsvgit approved these changes
Пойдёт!) Тепреь эксперименты и отчёт.

2023-02-23 14:53 UTC, merged