Homework 2
artem-burashnikov/2022-Programming-Technologies-F-sharp-course pull request #9
Opened 2022-10-05 01:40 UTC by artem-burashnikov

## Proposed Changes

I have added all the requested functions and tests.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Build and tests pass locally
- [ ] Concat for MyList
- [ ] Concat for MyOOPList
- [ ] Bubble sort for MyList
- [ ] Bubble sort for MyOOPList
- [ ] QuickSort for MyList
- [ ] QuickSort for MyOOPList
- [ ] Custom types generator for property and case testing via FsCheck

## Further comments

Please, ignore any errors related to building for now.
There are also plenty of issues with Tests that require further investigation.

2022-10-05 06:15 UTC, gsvgit requested changes

2022-10-05 06:15 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
Эта функция очень похожа на ```biggerElements```. Можно ли их как-то унифицировать?

2022-10-05 06:15 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                    (concat
Зачем здесь ```concat```?

2022-10-05 06:15 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +        | _ -> failwith "Task2.bubbleSortOOP.sort: IList type was expected."
А кого получили?

2022-10-05 06:15 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: IList<'value>) (pivot: 'value) : IList<'value> =
И снова две очень похожие функции.

2022-10-05 06:15 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                        (concatOOP
И снова потенциально лишняя конкатенация.

2022-10-05 06:15 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +    type MyComparableValues =
Хитро, конечно, но...
1. А правда ли, что обёртки сравниваются как базовые типы?
2. А если я вспомню, что бывают ещё какие-нибудь типы, которые можно сортировать?

2022-10-05 06:15 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            // TODO Make a custom type generator
Если сложно, то можно просто реализовать конвертатор из системного списка.

2022-10-05 19:42 UTC, artem-burashnikov commented on src/spbu-fsharp/Task2.fs
> +                    (concat
Чтобы соединить левую отсортированную часть, pivot и правую отсортированную часть.
Соединять вроде бы в любом случае придется. Не вижу, как без соединения можно.

2022-10-05 19:58 UTC, artem-burashnikov commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
Пока что идеи, что с ними сделать, две:
1) Возвращать одной функцией кортеж двух результатов, а потом распаковывать
2) Сделать одну функцию, которой передавать дополнительный аргумент, отвечающий за то, как нужно сравнивать.
Но кажется, будто оба эти решения будут громоздкими и менее читабельными.
Возможно, есть еще какое-то хитрое обобщение работы функции, но пока не вижу.

Лиюо вообще реализацию изменить так, что понадобится лишь одна функция, которая только сравнивает либо "<", либо ">" и в одном случае что-то делает, а в другом - нет.

2022-10-06 05:37 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                    (concat
Concat - дорогая операция. Если я правильно понимаю происходящее, то тут pivot  можно приклеить к другой половине гораздо дешевле.

2022-10-06 05:40 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
1. Додумайте второй вариант. Вы же можете передавать функции как аргументы. Но он все равно не самый лучший. Подумайте, почему. 
2. Если первый вариант сделать аккуратно, то он будет самым разумным.

2022-10-06 07:58 UTC, LeonidLodygin commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
Понятно, что в рамках данной задачи создавать кортеж(идея Артема) это лучший вариант, чтобы лишний раз не пробегать по списку. Но что, если данная функция будет использоваться в дальнейшем, когда нам нужен будет только список из меньших или больших элементов. Тогда мы будем захламлять память лишними данными.(вторым списком). Является ли тогда такая реализация все равно самой разумной?

2022-10-06 08:04 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
@LeonidLodygin Вы правы. В том смысле, что данное решение не универсально. Но мы пока про данную конкретную задачу.

2022-10-06 23:39 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            // TODO Make a custom type generator
При вызове вот такого теста
![image](https://user-images.githubusercontent.com/94160707/194437026-a543a8c2-4ce9-469c-943a-13dac635b8a5.png)

Возникает вот такая проблема
![image](https://user-images.githubusercontent.com/94160707/194436965-1ee455d7-84e7-4760-9367-179d2340cd3a.png)

При этом конвертеры из системного списка и обратно написаны и протестированы, то есть вероятность ошибка там сравнительно малая.
Собственно, победить эту ошибку получается только с помощью задания типов, про которые заранее известно, что их можно сравнивать (например, int). Причем на float у меня возникает еще одна проблема, когда actualResult и expectedResult равны, но "сравнитель" выдаёт, что они не похожи. 
Например, Cons (Floats nan, Empty) не сравнивается с самим собой.

2022-10-06 23:55 UTC, artem-burashnikov commented on src/spbu-fsharp/Task2.fs
> +        let rec smallerElements (lst: MyList<'value>) (pivot: 'value) : MyList<'value> =
В последнем коммите реализована унифицированная функция, которая возвращает кортеж.

2022-10-06 23:55 UTC, artem-burashnikov commented on src/spbu-fsharp/Task2.fs
> +                    (concat
Лишний concat убрал.

2022-10-07 06:27 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            // TODO Make a custom type generator
Да, он прав. придётся несколько тестов написать в духе 
``` <| fun (lst:list<int>) -> ... ```
``` <| fun (lst:list<string>) -> ... ```
``` <| fun (lst:list<float>) -> ... ```

2022-10-07 06:32 UTC, gsvgit requested changes

2022-10-07 06:32 UTC, gsvgit commented on src/spbu-fsharp/Task1.fs
> +    let smallerNum =
Даже если Вы решили провести рефакторинг, то не надо пихать всё в одну кучу. Какое отношение это изменение имеет к сдаваемой домашке?

2022-10-07 06:32 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                        Cons(head, fst (partition tail pivot)), snd (partition tail pivot)
Зачем два раза считать одно и то же?

2022-10-07 06:32 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                        (sort (fst <| partition tail head))
И тут два раза одно и то же считаете.

2022-10-07 06:32 UTC, gsvgit commented on src/spbu-fsharp/Task2.fs
> +                            MyOOPNonEmptyList(lst.Head, fst <| partition lst.Tail pivot),
И тут повторные вычисления.

2022-10-07 06:32 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task1Tests.fs
>  open HomeWork1
Кажется, это тоже не имеет отношения к сдаваемой домашке.

2022-10-07 10:41 UTC, artem-burashnikov commented on src/spbu-fsharp/Task1.fs
> +    let smallerNum =
Не планировал сюда заливать, случайно, извиняюсь.

2022-10-07 10:42 UTC, artem-burashnikov commented on src/spbu-fsharp/Task2.fs
> +                            MyOOPNonEmptyList(lst.Head, fst <| partition lst.Tail pivot),
Поправил.

2022-10-08 08:27 UTC, artem-burashnikov commented
https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/pull/9#discussion_r988570761
- [x] Функция реализована таким образом, что она проходится по списко один раз и результатом работы возвращает кортеж значений.

https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/pull/9#discussion_r988569186
- [x] Убрал лишний concat.

https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/pull/9#discussion_r987565538
 - [x] Изменил вывод об ошибке.

https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/pull/9#discussion_r987566797
https://github.com/artem-burashnikov/2022-Programming-Technologies-F-sharp-course/pull/9#discussion_r989722867
- [x] Добавил тесты.

2022-10-08 08:30 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task1Tests.fs
>  open HomeWork1
Как я понял, это уже не убрать из текущего PR, и единственный способ - следить, чтобы оно не попадало в PR изначально.

2022-10-08 15:51 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task1Tests.fs
>  open HomeWork1
Ну как... Можно закрыть этот реквест, сделать новую ветку от правильного места, переложить в неё толькот то, что надо, открыть новый реквест.

2022-10-08 15:57 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> MyOOPList -> MyList -> List should return the original list"
А если десять раз преобразовать?

2022-10-08 15:57 UTC, gsvgit commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> List should return the original list"
Крайние случаи лучше касё равно явно проверять. Сортировка пустого списка, например. Может ещё что-то нетривиальное есть.

2022-10-08 17:00 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> MyOOPList -> MyList -> List should return the original list"
Вы имеете в виду, что функция должна давать один и тот же результат на одни и те же входные данные?
Двух раз не хватит в таком случае?

2022-10-08 17:20 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> MyOOPList -> MyList -> List should return the original list"
![image](https://user-images.githubusercontent.com/94160707/194719694-3d9d24d5-4091-45b5-99a3-707c49e4fc7d.png)
Можно и десять...

2022-10-08 17:36 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> MyOOPList -> MyList -> List should return the original list"
@gsvgit Или вы конкретно хотите, чтобы я её прогнал 10 раз?..

2022-10-08 17:39 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> List should return the original list"
Есть такие мысли:
1-ый Нетривиальный случай - пустой список.
2-ой Нетрвивиальный случай - список из 1 элемента (может быть какие-нибудь подслучаи рассмотреть).
3-ий Нетривиальный случай - список из 2 элементов (тоже рассмотреть подслучаи).
А далее мы умеем сортировать и уверены в правильности сортировки для количества элементов > 2, так как сортируем рекурсией.

2022-10-08 18:43 UTC, artem-burashnikov commented on tests/spbu-fsharp.Tests/Task2Tests.fs
> +            testProperty "List -> MyList -> MyOOPList -> MyList -> List should return the original list"
Этот тест на конвертацию из MyList -> MyOOPList (MyOOPList -> MyList) но, чтобы не сравнивать их между собой, я по бокам прилепил системные списки, которые легко генерируются и сравниваются.

2022-10-08 21:11 UTC, closed without merging